### ISSUE TITLE
sweep error due to incorrect key

### ISSUE THREAD

**Issue by avlsi** [dreoilin/pygmid#22]
python3 -m pygmid --mode sweep --config config_pdk.cfg                                                                                               
Sweeping L:   0%|                                                                                                                                               | 0/58 [00:00<?, ?it/s
Process Process-1:%|##############6                                                                                                          | 1/11 [00:11<01:59, 11.96s/it]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/psf_utils/psf.py", line 225, in get_signal
    return self.signals[name]
KeyError: 'mn:gmbs'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/pygmid/sweep/sweep.py", line 97, in parse_sim
    (n_dict, p_dict) = self._extract_sweep_params(filepath)
  File "/home/user/.local/lib/python3.6/site-packages/pygmid/sweep/sweep.py", line 149, in _extract_sweep_params
    nmos[f'mn:{param}'][:,VDS_i] = (psf.get_signal(f"mn:{param}").ordinate).T
  File "/home/user/.local/lib/python3.6/site-packages/psf_utils/psf.py", line 227, in get_signal
    raise UnknownSignal(name, choices=self.signals.keys())
psf_utils.psf.UnknownSignal: unknown signal: mn:gmbs.

**Comment by avlsi** [comment]
The issue originates because of the type of model used. For example, we need different config.py files for different model types.

1. https://github.com/bmurmann/Book-on-gm-ID-design/blob/main/starter_kit/techsweep_config_bsim4_28_spectre.m
2. https://github.com/bmurmann/Book-on-gm-ID-design/blob/main/starter_kit/techsweep_config_bsimcmg_16_spectre.m
3. https://github.com/bmurmann/Book-on-gm-ID-design/blob/main/starter_kit/techsweep_config_psp_65_spectre.m

I was wondering whether updating the config with type of model and parsing a corresponding config.py would solve this problem.

**Comment by avlsi** [comment]
I am observing that there could be instances where the include files could be more than 1. can there be a feature to add more include lines to the configuration?

**Comment by dreoilin** [comment]
Hi avlsi. Thanks for your comment. This is a known issue. To characterise a BSIM model with non standard structure, you will have to modify and build the package from source. For example, one of our PDKs references a subcircuit which contains the small signal parameters. To rectify this, a custom build was written to reference the subcircuit i.e MN.m1

Another of our PDKs is similar to your situation: different keys are used for small signal parameters. In this case another custom build was created.

I don't have plans of modifying the package to account for all of these variations in model files. It is up to the end user to modify the config and sweep files in a custom build to achieve this.

**Comment by dreoilin** [comment]
In response to your second comment: yes, this is something I will add in the next package update
